version: '3.5'

networks:
  redis_network:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - redis_network

  bots:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - redis_network
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
